export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
# gsm8k & gsm8k-zeroshot
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0 --zero-shot
# codegen
python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
# squad
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
# mmlu-cot
python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
# cnn-dailymail
python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0
python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/debug_param_tune_3rounds/llama3-70b --rounds 3 --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 8192 --target-mem-util 1.0