export PYTHONPATH=/home/zhangyanqi/Projects/eLLM_dev:$PYTHONPATH
CUDA_VISIBLE_DEVICES=3 RAY_DEDUP_LOGS=0 python3 run_humaneval.py \
    --model mistralai/Mistral-7B-Instruct-v0.2 \
    --load-format safetensors \
    --download-dir /data/huggingface \
    --enforce-eager --dtype float16 \
    --kv-buffer-size 32 \
    --kbits-high 8 \
    --vbits-high 8 \
    --kbits-low 8 \
    --vbits-low 8 \
    --kv-prune-thresh 1.0 \
    --kv-quant-thresh 1.0 \
    --kv-prune-ratio 1.0 \
    --kv-quant-ratio 1.0 \
    --sampling-n 1 \
    --temperature 0 \
    --gpu-memory-utilization 0.75 \
    --max-num-batched-tokens 40000 \
    --max-paddings 4096 \
    --tensor-parallel-size 1 \
    --prompt-limit 3500 \
    --max-num-seqs 256 \
    --log-path ../tmp/debug/ \
    --data-label test \
    --indices-csv ../logs/param_tune_5rounds/mistral/humaneval_k1/k8v8_k8v8/target_10_buffer_32/p1000_q1000/round_0/sample_indices_0.csv