export PYTHONPATH=/home/zhangyanqi/Projects/eLLM_sparsity_profile:$PYTHONPATH
# # gsm8k 88-88
# # python3 emulate_qa_correct.py --dataset gsm8k --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 emulate_qa_correct.py --dataset gsm8k --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 0.5 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 emulate_qa_correct.py --dataset gsm8k --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 1.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 emulate_qa_correct.py --dataset gsm8k --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 1.5 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 emulate_qa_correct.py --dataset gsm8k --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 2.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # # # squad 84-42
# # python3 emulate_qa_rogue.py --dataset squad --model-gen 3 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 256 --target-mem-util 0.1 --rounds 1
# # mmlu 88-88
# # python3 emulate_qa_correct.py --dataset mmlu_cot --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_qa_correct.py --dataset mmlu_cot --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 0.5 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_qa_correct.py --dataset mmlu_cot --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 1.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_qa_correct.py --dataset mmlu_cot --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 1.5 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_qa_correct.py --dataset mmlu_cot --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --attn-prune-thresh 2.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# longbench 88-88
# python3 emulate_longbench.py --model-gen 3.1 --model-size 8 --sample-rate 20 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_longbench.py --model-gen 3.1 --model-size 8 --sample-rate 20 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 1.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_longbench.py --model-gen 3.1 --model-size 8 --sample-rate 20 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 1.5 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 emulate_longbench.py --model-gen 3.1 --model-size 8 --sample-rate 20 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 2.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# longbench 88-88
# python3 emulate_longbench_v2.py --model-gen 3.1 --model-size 8 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1 --num-samples 100
python3 emulate_longbench_v2.py --model-gen 3.1 --model-size 8 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 1.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1 --num-samples 100
python3 emulate_longbench_v2.py --model-gen 3.1 --model-size 8 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 1.5 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1 --num-samples 100
python3 emulate_longbench_v2.py --model-gen 3.1 --model-size 8 --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 2.0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1 --num-samples 100