export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
# gsm8k 42-41
python3 eval_qa_correct.py --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.995 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # squad 44-42
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_rogue.py --dataset squad --model-gen 2 --model-size 7  --log-path ../logs/new_kernel_param_tune_5rounds/llama2-7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.995 --kv-buffer 64 --target-mem-util 0.1 --rounds 1