export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
# gsm8k 84-42
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# # gsm8k 44-42
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# # gsm8k 42-41
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5 --zero-shot
# # humaneval 84-42
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # humaneval 44-42
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # humaneval 42-41
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# mmlu 84-42
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# mmlu 44-42
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # mmlu 42-41
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # squad 84-42
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # squad 42-41
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # squad 44-42
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_qa_rogue.py --dataset squad --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # cnn-dailymail 84-42
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # cnn-dailymail 44-42
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# # cnn-dailymail 42-41
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 64 --target-mem-util 0.1 --rounds 5
# python3 eval_summarize.py --dataset cnn_daily --model-gen 3 --model-size 70  --log-path ../logs/new_kernel_param_tune_5rounds/llama3-70b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 64 --target-mem-util 0.1 --rounds 5