export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
# baseline gsm8k 88-88
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline gsm8k-zeroshot 88-88
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
# baseline gsm8k 84-84
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline gsm8k-zeroshot 84-84
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
# baseline gsm8k 44-44
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline gsm8k-zeroshot 44-44
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
# baseline gsm8k 42-42
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline gsm8k-zeroshot 42-42
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
# gsm8k 84-42
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
# gsm8k 42-41
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5 --zero-shot
# baseline humaneval 88-88
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline humaneval 84-84
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline humaneval 44-44
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline humaneval 42-42
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# humaneval 84-42
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# humaneval 42-41
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9995 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9999 --kv-buffer 32 --target-mem-util 0.1 --rounds 5
# baseline mmlu 88-88
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline mmlu 84-84
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline mmlu 44-44
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline mmlu 42-42
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# mmlu 84-42
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# mmlu 42-41
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline squad 88-88
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline squad 84-84
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline squad 44-44
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline squad 42-42
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# squad 84-42
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# squad 42-41
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline cnn-dailymail 88-88
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline cnn-dailymail 84-84
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 8 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline cnn-dailymail 44-44
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# baseline cnn-dailymail 42-42
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# cnn-dailymail 84-42
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# cnn-dailymail 42-41
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.5 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.97 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 1.0 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3