export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
# gsm8k 84-42
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.9995 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.9995 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.9995 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.9999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.9999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.9999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
# gsm8k 42-41
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.85 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.9995 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.9995 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.9995 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.9999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.9999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
python3 eval_qa_correct.py --dataset gsm8k --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.9999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 3 --zero-shot
# humaneval 84-42
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.995 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# humaneval 42-41
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.995 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.8 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
python3 eval_codegen.py --dataset humaneval --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 3
# mmlu 84-42
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
# mmlu 42-41
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_qa_correct.py --dataset mmlu_cot --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
# squad 84-42
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
# squad 42-41
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_qa_rogue.py --dataset squad --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
# cnn-dailymail 84-42
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
# cnn-dailymail 42-41
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.9 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.95 --kv-buffer 32 --target-mem-util 0.1 --rounds 1
python3 eval_summarize.py --dataset cnn_daily --model mixtral --model-gen 1 --model-size 56  --log-path ../logs/param_tune_5rounds/mixtral-8x7b --kbits-high 4 --vbits-high 2 --kbits-low 4 --vbits-low 1 --kv-prune-thresh 0.999 --kv-quant-thresh 0.99 --kv-buffer 32 --target-mem-util 0.1 --rounds 1