export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
#---------------------------------- qwen2.5-7b
# # ******** gsm8k 88-88
# # python3 _eval_qa_correct.py --model qwen2 --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --model qwen2 --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset gsm8k --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 0.02   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # # ******** minerva_math 88-88
# python3 _eval_qa_correct.py --model qwen2 --dataset minerva_math --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset minerva_math --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --model qwen2 --dataset minerva_math --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset minerva_math --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 0.02   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# # # ******** humaneval
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 0.02  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.04 --kv-quant-thresh 0.04  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 0.08  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset humaneval --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.10 --kv-quant-thresh 0.10  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # ******** mbpp_plus
# python3 _eval_codegen.py --model qwen2 --dataset mbpp_plus --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset mbpp_plus --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_codegen.py --model qwen2 --dataset mbpp_plus --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --model qwen2 --dataset mbpp_plus --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02  --kv-quant-thresh 0.02  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # ******** mmlu 84-42
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02  --kv-quant-thresh 0.02  --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# # ******** mmlu-pro 84-42
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0   --kv-quant-thresh 0.0   --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02  --kv-quant-thresh 0.02  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.04  --kv-quant-thresh 0.04  --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08  --kv-quant-thresh 0.08  --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --model qwen2 --dataset mmlu_pro_cot --model-gen 2 --model-size 7  --log-path ../logs/per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.1   --kv-quant-thresh 0.1   --kv-buffer 64 --target-mem-util 0.1 --rounds 1
#---------------------------------- llama3-8b
# # ******** gsm8k 88-88
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 4.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.1 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # ******** minerva_math 88-88
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# # ******** humaneval
# python3 _eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # # ******** mbpp_plus
# python3 _eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 _eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # ******** mmlu 84-42
# python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 4.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.10 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# ******** mmlu-pro 84-42
python3 _eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
python3 _eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1