export PYTHONPATH=/home/zhangyanqi/git_repos/DiffKV:$PYTHONPATH
# # ******** gsm8k 88-88
python3 _eval_qa_correct.py --model llama --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --model llama --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --model llama --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --model llama --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --model llama --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --model llama --dataset gsm8k --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 3
# # ******** minerva_math 88-88
python3 _eval_qa_correct.py --model llama --dataset minerva_math --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset minerva_math --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset minerva_math --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset minerva_math --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset minerva_math --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 1
# ******** humaneval
python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
# python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset humaneval --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 3
# ******** mbpp_plus
python3 _eval_codegen.py --model llama --dataset mbpp_plus --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset mbpp_plus --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset mbpp_plus --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset mbpp_plus --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset mbpp_plus --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 3
python3 _eval_codegen.py --model llama --dataset mbpp_plus --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 3
# ******** mmlu 84-42
python3 _eval_qa_correct.py --model llama --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_cot --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 1
# # ******** mmlu-pro 84-42
python3 _eval_qa_correct.py --model llama --dataset mmlu_pro_cot --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_pro_cot --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_pro_cot --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_pro_cot --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_pro_cot --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --model llama --dataset mmlu_pro_cot --sample-rate 20 --model-gen 3 --model-size 70  --log-path ../logs/per_token_thresh/llama3-70b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 1