export PYTHONPATH=/home/zhangyanqi/git_repos/DiffKV:$PYTHONPATH
# ******** qwen2.5-32b minerva_math 88-88
# **** quant
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.5 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 4.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 1
# **** prune
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.04 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.06 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 32  --log-path ../logs/calibrate_per_token_thresh/qwen25-32b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.1  --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
# # ******** qwen2.5-7b minerva_math 88-88
# quant
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0  --kv-quant-thresh 1.0  --kv-buffer 64 --rounds 1
# # **** prune
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0  --kv-quant-thresh 0.0  --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 0.02 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.04 --kv-quant-thresh 0.04 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.06 --kv-quant-thresh 0.06 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 0.08 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.1  --kv-quant-thresh 0.1  --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.12 --kv-quant-thresh 0.12 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.14 --kv-quant-thresh 0.14 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.16 --kv-quant-thresh 0.16 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.18 --kv-quant-thresh 0.18 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model qwen2 --model-gen 2 --model-size 7  --log-path ../logs/calibrate_per_token_thresh/qwen25-7b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.2  --kv-quant-thresh 0.2  --kv-buffer 64 --rounds 1
# ******** llama3-8b minerva_math 88-88
# **** quant
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.5 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 3.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 4.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 5.0 --kv-buffer 64 --rounds 1
# **** prune
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.02 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.04 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.06 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.08 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.10 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.12 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.14 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.16 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.18 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.20 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 1