export PYTHONPATH=/home/zhangyanqi/Projects/eLLM:$PYTHONPATH
# ******** gsm8k 88-88
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gsm8k --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# ******** minerva_math 88-88
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
python3 eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # ******** humaneval
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset humaneval --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # ******** mbpp_plus
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_codegen.py --dataset mbpp_plus --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# # # # squad 84-42
# # python3 emulate_qa_rogue.py --dataset squad --model-gen 3 --model-size 8  --log-path ../logs/emulate_5rounds/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 1.0 --kv-quant-thresh 0.95 --kv-buffer 256 --target-mem-util 0.1 --rounds 1
# ******** mmlu 84-42
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# ******** mmlu-pro 84-42
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset mmlu_pro_cot --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# ******** gpqa 84-42
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# python3 eval_qa_correct.py --dataset gpqa --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 3
# ******** wiki 84-42
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# python3 eval_wiki.py --dataset wiki --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --num-lines 100000 --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1
# # ******** longbench 88-88
# # python3 emulate_longbench.py --model-gen 3.1 --model-size 8  --log-path ../logs/emulate_5rounds/llama3.1-8b --attn-prune-thresh 0 --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 1.0 --kv-quant-thresh 1.0 --kv-buffer 64 --target-mem-util 0.1 --rounds 1