export PYTHONPATH=/home/zhangyanqi/git_repos/DiffKV:$PYTHONPATH
# ******** minerva_math 88-88
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 8 --kbits-low 8 --vbits-low 8 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3
# python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.1 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.2 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.3 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.4 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.5 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.6 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.7 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 0.8 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.0 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.2 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.4 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.6 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 1.8 --kv-buffer 64 --rounds 3
python3 _eval_qa_correct.py --dataset minerva_math --label train --model-gen 3 --model-size 8  --log-path ../logs/calibrate_per_token_thresh/llama3-8b --kbits-high 8 --vbits-high 4 --kbits-low 4 --vbits-low 2 --kv-prune-thresh 0.0 --kv-quant-thresh 2.0 --kv-buffer 64 --rounds 3
# python3 _eval_qa_correct.py --dataset minerva_math --model-gen 3 --model-size 8  --log-path ../logs/per_token_thresh/llama3-8b --kbits-high 4 --vbits-high 4 --kbits-low 4 --vbits-low 4 --kv-prune-thresh 0.0 --kv-quant-thresh 0.0 --kv-buffer 64 --rounds 3